/* Populated by react-webpack-redux:action */
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const GET_SESSIONS = 'GET_SESSIONS';
export const UPDATE_REVIEWS = 'UPDATE_REVIEWS';
export const UPDATE_USERS = 'UPDATE_USERS';
export const UPDATE_SESSION_ID = 'UPDATE_SESSION_ID';
export const UPDATE_IS_LOGIN = 'UPDATE_IS_LOGIN';
export const SELECT_REVIEW_TYPE = 'SELECT_REVIEW_TYPE';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
