import React from 'react';
import { RaisedButton, TextField } from 'material-ui';

class CreateForm extends React.Component {

  render() {

    const { nameFieldErrorMsg, name, nameHandleChange, submitSessionDetails} = this.props;
    const noteStyle = {
      position: 'relative',
      fontSize: '12px',
      lineHeight: '12px',
    };

    return (
      <form onSubmit={submitSessionDetails}>
        <TextField
          errorText={nameFieldErrorMsg}
          floatingLabelText="Name"
          value={name}
          onChange={nameHandleChange}
          fullWidth={true}
        />
        <div style={noteStyle}>
          <span style={{color:'orange'}}><b>Note:</b> A session ID will be auto-generated by the database.</span>
        </div>
        <RaisedButton type="submit" label="Submit" primary={true} style={{ marginTop: '26px' }} />
      </form>
    );
  }
}

CreateForm.displayName = 'ModalLoginCreateForm';
CreateForm.propTypes = {};
CreateForm.defaultProps = {};

export default CreateForm;
